DROP TABLE IF EXISTS User;
CREATE TABLE `User` (
	`id` int(8) NOT NULL AUTO_INCREMENT,
	`name` varchar(25) DEFAULT 'null',
	`age` int DEFAULT '0',
	`isAdmin` bit NOT NULL,
	`createdDate` TIMESTAMP NOT NULL,
	PRIMARY KEY (`id`)
);
INSERT INTO User(name, age, isAdmin) values ('Anton', 20, 0);
INSERT INTO User(name, age, isAdmin) values ('Kolya', 30, 1);
INSERT INTO User(name, age, isAdmin) values ('Petya', 15, 0);
INSERT INTO User(name, age, isAdmin) values ('Misha', 10, 1);
INSERT INTO User(name, age, isAdmin) values ('Zahar', 3, 0);
INSERT INTO User(name, age, isAdmin) values ('Anya', 50, 0);
INSERT INTO User(name, age, isAdmin) values ('Olya', 18, 1);
INSERT INTO User(name, age, isAdmin) values ('Ivan Ivanovich', 46, 0);
INSERT INTO User(name, age, isAdmin) values ('Gulchatai', 35, 1);
INSERT INTO User(name, age, isAdmin) values ('Anton', 131, 0);
INSERT INTO User(name, age, isAdmin) values ('Sergei', 15, 0);
INSERT INTO User(name, age, isAdmin) values ('Yulia', 38, 1);
INSERT INTO User(name, age, isAdmin) values ('Alexandr', 3, 0);
INSERT INTO User(name, age, isAdmin) values ('Masha', 20, 0);
INSERT INTO User(name, age, isAdmin) values ('Irina Afanasievna', 120, 0);
INSERT INTO User(name, age, isAdmin) values ('Serafima', 40, 0);
INSERT INTO User(name, age, isAdmin) values ('Valentina', 70, 0);
INSERT INTO User(name, age, isAdmin) values ('Petr', 23, 0);
INSERT INTO User(name, age, isAdmin) values ('Iisus', 33, 0);
INSERT INTO User(name, age, isAdmin) values ('Oleg', 35, 0);
INSERT INTO User(name, age, isAdmin) values ('Shura', 40, 0);
INSERT INTO User(name, age, isAdmin) values ('Anton', 20, 0);
INSERT INTO User(name, age, isAdmin) values ('Kolya', 30, 1);
INSERT INTO User(name, age, isAdmin) values ('Petya', 15, 0);
INSERT INTO User(name, age, isAdmin) values ('Misha', 10, 1);
INSERT INTO User(name, age, isAdmin) values ('Zahar', 3, 0);
INSERT INTO User(name, age, isAdmin) values ('Anya', 50, 0);
INSERT INTO User(name, age, isAdmin) values ('Olya', 18, 1);
INSERT INTO User(name, age, isAdmin) values ('Ivan Ivanovich', 46, 0);
INSERT INTO User(name, age, isAdmin) values ('Gulchatai', 35, 1);
INSERT INTO User(name, age, isAdmin) values ('Anton', 131, 0);
INSERT INTO User(name, age, isAdmin) values ('Sergei', 15, 0);
INSERT INTO User(name, age, isAdmin) values ('Yulia', 38, 1);
INSERT INTO User(name, age, isAdmin) values ('Alexandr', 3, 0);
INSERT INTO User(name, age, isAdmin) values ('Masha', 20, 0);
INSERT INTO User(name, age, isAdmin) values ('Irina Afanasievna', 120, 0);
INSERT INTO User(name, age, isAdmin) values ('Serafima', 40, 0);
INSERT INTO User(name, age, isAdmin) values ('Valentina', 70, 0);
INSERT INTO User(name, age, isAdmin) values ('Petr', 23, 0);
INSERT INTO User(name, age, isAdmin) values ('Iisus', 33, 0);
INSERT INTO User(name, age, isAdmin) values ('Oleg', 35, 0);
INSERT INTO User(name, age, isAdmin) values ('Shura', 40, 0);
INSERT INTO User(name, age, isAdmin) values ('Ivan Ivanovich', 46, 0);
INSERT INTO User(name, age, isAdmin) values ('Gulchatai', 35, 1);
INSERT INTO User(name, age, isAdmin) values ('Anton', 131, 0);
INSERT INTO User(name, age, isAdmin) values ('Sergei', 15, 0);
INSERT INTO User(name, age, isAdmin) values ('Yulia', 38, 1);
INSERT INTO User(name, age, isAdmin) values ('Alexandr', 3, 0);
INSERT INTO User(name, age, isAdmin) values ('Masha', 20, 0);
INSERT INTO User(name, age, isAdmin) values ('Irina Afanasievna', 120, 0);
INSERT INTO User(name, age, isAdmin) values ('Serafima', 40, 0);
INSERT INTO User(name, age, isAdmin) values ('Valentina', 70, 0);
INSERT INTO User(name, age, isAdmin) values ('Petr', 23, 0);
INSERT INTO User(name, age, isAdmin) values ('Iisus', 33, 0);
INSERT INTO User(name, age, isAdmin) values ('Oleg', 35, 0);
INSERT INTO User(name, age, isAdmin) values ('Shura', 40, 0);
INSERT INTO User(name, age, isAdmin) values ('Alexandr', 3, 0);
INSERT INTO User(name, age, isAdmin) values ('Masha', 20, 0);
INSERT INTO User(name, age, isAdmin) values ('Irina Afanasievna', 120, 0);
INSERT INTO User(name, age, isAdmin) values ('Serafima', 40, 0);
INSERT INTO User(name, age, isAdmin) values ('Valentina', 70, 0);
INSERT INTO User(name, age, isAdmin) values ('Petr', 23, 0);
INSERT INTO User(name, age, isAdmin) values ('Iisus', 33, 0);
INSERT INTO User(name, age, isAdmin) values ('Oleg', 35, 0);
INSERT INTO User(name, age, isAdmin) values ('Shura', 40, 0);
INSERT INTO User(name, age, isAdmin) values ('Ivan Ivanovich', 46, 0);
INSERT INTO User(name, age, isAdmin) values ('Gulchatai', 35, 1);
INSERT INTO User(name, age, isAdmin) values ('Anton', 131, 0);
INSERT INTO User(name, age, isAdmin) values ('Sergei', 15, 0);
INSERT INTO User(name, age, isAdmin) values ('Yulia', 38, 1);
INSERT INTO User(name, age, isAdmin) values ('Alexandr', 3, 0);
INSERT INTO User(name, age, isAdmin) values ('Masha', 20, 0);
INSERT INTO User(name, age, isAdmin) values ('Irina Afanasievna', 120, 0);
INSERT INTO User(name, age, isAdmin) values ('Serafima', 40, 0);
INSERT INTO User(name, age, isAdmin) values ('Valentina', 70, 0);
INSERT INTO User(name, age, isAdmin) values ('Petr', 23, 0);
INSERT INTO User(name, age, isAdmin) values ('Iisus', 33, 0);
INSERT INTO User(name, age, isAdmin) values ('Oleg', 35, 0);
INSERT INTO User(name, age, isAdmin) values ('Shura', 40, 0);
INSERT INTO User(name, age, isAdmin) values ('Iisus', 33, 0);
INSERT INTO User(name, age, isAdmin) values ('Oleg', 35, 0);
INSERT INTO User(name, age, isAdmin) values ('Shura', 40, 0);
INSERT INTO User(name, age, isAdmin) values ('Alexandr', 3, 0);
INSERT INTO User(name, age, isAdmin) values ('Masha', 20, 0);
INSERT INTO User(name, age, isAdmin) values ('Irina Afanasievna', 120, 0);
INSERT INTO User(name, age, isAdmin) values ('Serafima', 40, 0);
INSERT INTO User(name, age, isAdmin) values ('Valentina', 70, 0);
INSERT INTO User(name, age, isAdmin) values ('Petr', 23, 0);
INSERT INTO User(name, age, isAdmin) values ('Iisus', 33, 0);
INSERT INTO User(name, age, isAdmin) values ('Oleg', 35, 0);
INSERT INTO User(name, age, isAdmin) values ('Shura', 40, 0);
INSERT INTO User(name, age, isAdmin) values ('Ivan Ivanovich', 46, 0);
INSERT INTO User(name, age, isAdmin) values ('Gulchatai', 35, 1);
INSERT INTO User(name, age, isAdmin) values ('Anton', 131, 0);
INSERT INTO User(name, age, isAdmin) values ('Sergei', 15, 0);
INSERT INTO User(name, age, isAdmin) values ('Yulia', 38, 1);
INSERT INTO User(name, age, isAdmin) values ('Alexandr', 3, 0);
INSERT INTO User(name, age, isAdmin) values ('Masha', 20, 0);
INSERT INTO User(name, age, isAdmin) values ('Irina Afanasievna', 120, 0);
INSERT INTO User(name, age, isAdmin) values ('Serafima', 40, 0);
INSERT INTO User(name, age, isAdmin) values ('Valentina', 70, 0);
INSERT INTO User(name, age, isAdmin) values ('Petr', 23, 0);
INSERT INTO User(name, age, isAdmin) values ('Iisus', 33, 0);
INSERT INTO User(name, age, isAdmin) values ('Oleg', 35, 0);
INSERT INTO User(name, age, isAdmin) values ('Shura', 40, 0);
INSERT INTO User(name, age, isAdmin) values ('Iisus', 33, 0);
INSERT INTO User(name, age, isAdmin) values ('Oleg', 35, 0);
INSERT INTO User(name, age, isAdmin) values ('Shura', 40, 0);
INSERT INTO User(name, age, isAdmin) values ('Alexandr', 3, 0);
INSERT INTO User(name, age, isAdmin) values ('Masha', 20, 0);
INSERT INTO User(name, age, isAdmin) values ('Irina Afanasievna', 120, 0);
INSERT INTO User(name, age, isAdmin) values ('Serafima', 40, 0);
INSERT INTO User(name, age, isAdmin) values ('Valentina', 70, 0);
INSERT INTO User(name, age, isAdmin) values ('Petr', 23, 0);
INSERT INTO User(name, age, isAdmin) values ('Iisus', 33, 0);
INSERT INTO User(name, age, isAdmin) values ('Oleg', 35, 0);
INSERT INTO User(name, age, isAdmin) values ('Shura', 40, 0);
INSERT INTO User(name, age, isAdmin) values ('Ivan Ivanovich', 46, 0);
INSERT INTO User(name, age, isAdmin) values ('Gulchatai', 35, 1);
INSERT INTO User(name, age, isAdmin) values ('Anton', 131, 0);
INSERT INTO User(name, age, isAdmin) values ('Sergei', 15, 0);
INSERT INTO User(name, age, isAdmin) values ('Yulia', 38, 1);
INSERT INTO User(name, age, isAdmin) values ('Alexandr', 3, 0);
INSERT INTO User(name, age, isAdmin) values ('Masha', 20, 0);
INSERT INTO User(name, age, isAdmin) values ('Irina Afanasievna', 120, 0);
INSERT INTO User(name, age, isAdmin) values ('Serafima', 40, 0);
INSERT INTO User(name, age, isAdmin) values ('Valentina', 70, 0);
INSERT INTO User(name, age, isAdmin) values ('Petr', 23, 0);
INSERT INTO User(name, age, isAdmin) values ('Iisus', 33, 0);
INSERT INTO User(name, age, isAdmin) values ('Oleg', 35, 0);
INSERT INTO User(name, age, isAdmin) values ('Shura', 40, 0);